source "https://rubygems.org"

gem "jekyll", "~> 3.9.3"
gem "jekyll-theme-cayman"
gem "kramdown-parser-gfm"
gem "webrick"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "github-pages", group: :jekyll_plugins
